### ISSUE TITLE
Robot UR3 can't control if attach the Gripper

### ISSUE THREAD

**Issue by KhuuLuanThanh** [ekorudiawan/rg2_simulation#1]
Hello Sir, i have done the rg2_gripper single simulation, but i have some problem using the gripper with ur3 robot. When I attach the gripper, the robot can't be controlled, but when I remove the gripper, it still controls normally.

 here are the errors i got, can you guide me to fix these problems okay.
When i run: ur3_planning_moveit:
`[ WARN] [1625667071.430583006]: Skipping virtual joint 'fixed_base' because its child frame 'base_link' does not match the URDF frame 'world'
[ INFO] [1625667071.430825332]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ERROR] [1625667072.175123934, 217.339000000]: Joint 'l_finger_2_joint' cannot mimic unknown joint 'gripper'
[ERROR] [1625667072.176298146, 217.340000000]: Joint 'l_finger_passive_joint' cannot mimic unknown joint 'gripper'
[ERROR] [1625667072.176329367, 217.340000000]: Joint 'r_finger_1_joint' cannot mimic unknown joint 'gripper'
[ERROR] [1625667072.176344731, 217.340000000]: Joint 'r_finger_2_joint' cannot mimic unknown joint 'gripper'
[ERROR] [1625667072.176359575, 217.340000000]: Joint 'r_finger_passive_joint' cannot mimic unknown joint 'gripper'
`

`[ WARN] [1625667075.622679656, 219.196000000]: The complete state of the robot is not yet known.  Missing l_finger_2_joint, l_finger_passive_joint, r_finger_1_joint, r_finger_2_joint, r_finger_passive_joint
`
When i run: file control ( python):
`[rospack] Error: package 'rg2_description' not found
[librospack]: error while executing command
[ERROR] [1625667146.640112965, 258.516000000]: Error retrieving file [package://rg2_description/meshes/collision/RG2_RightTrussArm_col.STL]: Package [rg2_description] does not exist
[rospack] Error: package 'rg2_description' not found
[librospack]: error while executing command
[ERROR] [1625667146.717391426, 258.544000000]: Error retrieving file [package://rg2_description/meshes/visual/RG2_RightTrussArm_vis.STL]: Package [rg2_description] does not exist
[ERROR] [1625667146.718064709, 258.544000000]: Joint 'l_finger_2_joint' cannot mimic unknown joint 'gripper'
[ERROR] [1625667146.718135386, 258.544000000]: Joint 'l_finger_passive_joint' cannot mimic unknown joint 'gripper'
[ERROR] [1625667146.718192303, 258.544000000]: Joint 'r_finger_1_joint' cannot mimic unknown joint 'gripper'
[ERROR] [1625667146.718282379, 258.544000000]: Joint 'r_finger_2_joint' cannot mimic unknown joint 'gripper'
[ERROR] [1625667146.718913554, 258.544000000]: Joint 'r_finger_passive_joint' cannot mimic unknown joint 'gripper'
[ INFO] [1625667148.067431775, 259.280000000]: Ready to take commands for planning group manipulator.
[ INFO] [1625667148.770734495, 259.655000000]: Ready to take commands for planning group manipulator.
[ INFO] [1625667149.437343952, 259.931000000]: ABORTED: No motion plan found. No execution attempted.
[ INFO] [1625667149.770409915, 260.069000000]: ABORTED: No motion plan found. No execution attempted.
[ INFO] [1625667150.116945914, 260.210000000]: ABORTED: No motion plan found. No execution attempted.
`
this is my urdf file: 
[ur3_urdf_xacro.txt](https://github.com/ekorudiawan/rg2_simulation/files/6778212/ur3_urdf_xacro.txt)

**Comment by Ugaux** [comment]
I found the problem : simply rename every "gripper" by "gripper_joint" in the rg2.urdf.xacro file and everything will be working smoothly.

**Comment by KhuuLuanThanh** [comment]
thanks for your help, it worked @Ugaux
